name: Multi-platform Build
on:
  push:
    branches:
      - master
      - action-test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
        use_static: [ON, OFF]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install CMake for Windows
        if: ${{ matrix.os }} == "windows-latest"
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ffmpeg --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Install CMake for Ubuntu
        if: ${{ matrix.os }} == "ubuntu-latest"
        run: |
          sudo apt update
          sudo apt-get install -y cmake ffmpeg
      - name: Install CMake for Macos
        if: ${{ matrix.os }} == "macos-latest"
            brew install cmake ffmpeg
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_STATIC=${{ matrix.use_static }} ..
          cmake --build . --config ${{ matrix.build_type }}
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.os }} == "windows-latest"
        with:
          name: release
          path: |
            build/${{ matrix.build_type }}/rtc.*
